---
abstract: 'A plugin for writing RESTful apps with Dancer'
author:
  - 'David Zurborg <zurborg@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-CRUD
no_index:
  directory:
    - t
    - inc
requires:
  Dancer: 1.312
  Modern::Perl: 0
  Sub::Name: 0
  Test::More: 0
  Text::Pluralize: 1.1
  Validate::Tiny: 1.005
version: 1.03
